FROM golang:alpine

RUN apk add git

WORKDIR /chat_stranger

EXPOSE 8080 

ARG ARG_POSTGRES_HOST=192.168.99.100
ARG ARG_POSTGRES_PORT=54320
ARG ARG_POSTGRES_USER=postgres
ARG ARG_POSTGRES_DB=postgres

ENV POSTGRES_HOST=$ARG_POSTGRES_HOST
ENV POSTGRES_PORT=$ARG_POSTGRES_PORT
ENV POSTGRES_USER=$ARG_POSTGRES_USER
ENV POSTGRES_DB=$ARG_POSTGRES_DB

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go install ./...

CMD ["chat_stranger"]
